/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-error-container": "#93000a",
        "on-surface": "#0b1c30",
        "surface-container": "#e5eeff",
        "surface-container-lowest": "#ffffff",
        "inverse-primary": "#bec6e0",
        "surface": "#f8f9ff",
        "secondary": "#0051d5",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed": "#00174b",
        "on-primary-fixed-variant": "#3f465c",
        "tertiary-fixed-dim": "#d2bbff",
        "outline-variant": "#c6c6cd",
        "primary-fixed-dim": "#bec6e0",
        "on-secondary-fixed-variant": "#003ea8",
        "on-tertiary-container": "#9863ff",
        "surface-variant": "#d3e4fe",
        "on-surface-variant": "#45464d",
        "error-container": "#ffdad6",
        "surface-container-low": "#eff4ff",
        "tertiary": "#000000",
        "surface-dim": "#cbdbf5",
        "tertiary-container": "#25005a",
        "on-primary-container": "#7c839b",
        "on-secondary-container": "#fefcff",
        "on-secondary": "#ffffff",
        "secondary-fixed": "#dbe1ff",
        "inverse-on-surface": "#eaf1ff",
        "primary-container": "#131b2e",
        "on-background": "#0b1c30",
        "secondary-fixed-dim": "#b4c5ff",
        "background": "#f8f9ff",
        "on-primary-fixed": "#131b2e",
        "outline": "#76777d",
        "on-tertiary-fixed": "#25005a",
        "on-error": "#ffffff",
        "surface-tint": "#565e74",
        "on-primary": "#ffffff",
        "on-tertiary-fixed-variant": "#5a00c6",
        "surface-container-high": "#dce9ff",
        "tertiary-fixed": "#eaddff",
        "secondary-container": "#316bf3",
        "inverse-surface": "#213145",
        "surface-container-highest": "#d3e4fe",
        "error": "#ba1a1a",
        "primary-fixed": "#dae2fd",
        "primary": "#000000",
        "surface-bright": "#f8f9ff",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "space-lg": "1rem",
        "gutter-compact": "0.5rem",
        "margin-mobile": "1rem",
        "space-xl": "1.5rem",
        "space-sm": "0.5rem",
        "space-2xs": "0.125rem",
        "space-2xl": "2rem",
        "space-xs": "0.25rem",
        margin: "1.5rem",
        gutter: "1rem",
        "space-md": "0.75rem",
      },
      fontFamily: {
        "label-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "mono-data-sm": ["JetBrains Mono", "monospace"],
        "mono-data-md": ["JetBrains Mono", "monospace"],
        "mono-data-lg": ["JetBrains Mono", "monospace"],
        "label-md": ["Inter", "sans-serif"],
      },
      fontSize: {
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.03em", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "headline-sm": ["16px", { lineHeight: "24px", letterSpacing: "-0.005em", fontWeight: "600" }],
        "display-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["24px", { lineHeight: "32px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "headline-md": ["20px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "mono-data-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "mono-data-md": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "mono-data-lg": ["24px", { lineHeight: "28px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
}


